spring:
  datasource:
    #    url: jdbc:mysql://db:3306/mydb
    url: jdbc:mysql://212.111.203.173:3306/mydb
    username: root
    password: rootpassword
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect